name: 'Changelog'
description: 'Returns a changelog since last successful deployment'
inputs:
  jira-host:
    required: true
  jira-username:
    required: true
  jira-password:
    required: true
  token:
    required: true
  slack-channel:
    required: true
  slack-token:
    required: true
  version:
    required: false
  job-status: 
    required: false
outputs:
  changelog:
    description: 'Changelog'
runs:
  using: 'node18'
  main: './dist/index.js'
