# action.yml
name: 'Cancel when already running'
description: 'Cancel when already running'

inputs:
  token:
    required: true
    description: 'Github Token'
  repo:
    required: true
    description: 'Repository Name'
  deployEnv:
    required: true
    description: 'GH Deployment Environment'
outputs:
  skip:
    description: 'Skip Deployment'

runs:
  using: 'composite'
  steps:
    - name: Cancel when already running
      id: skip
      run: |
        if [ "${{ inputs.deployEnv }}" = "stage" ]; then
          environment="stage"
        elif [ "${{ inputs.deployEnv }}" = "production" ]; then
          environment="production"
        fi

        workflows=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/OsomePteLtd/${{ inputs.repo }}/actions/runs | jq -r ".workflow_runs | .[]")
        echo $workflows | jq -rc '.name + " " + .status + " " + .display_title' |
        while read -r name status env; do
          if [ "$name" = "Deploy" ] && [ "$status" = "in_progress" ] && [ "$env" = "$environment" ]; then
            echo "$name -> $status -> $env"
            echo "Workflow with the same name already running"
            echo "skip=true" >> $GITHUB_OUTPUT
          fi
        done
      shell: bash
