name: 'Get deployment stages'
description: 'Get deployment stages'
inputs:
  token:
    description: 'Personal access token'
    required: false
  with-transient:
    description: 'Suggest transient environments'
    required: false
    default: 'true'
outputs:
  stages:
    description: 'List of environments'
runs:
  using: 'node12'
  main: './dist/index.js'
