name: 'Update spec'
description: 'Updates specs, commits and pushes updated types'
inputs:
  token:
    description: 'Github Token'
    required: true
  npm:
    description: 'NPM Token'
    required: true
runs:
  using: 'node16'
  main: './dist/index.js'
