# action.yml
name: 'Check Last Version'
description: 'Check last version from last main'

inputs:
  token:
    required: true
    description: 'Github Token'
  currentTag:
    required: true
    description: 'Current Project Tag'
  repo:
    required: true
    description: 'Repository Name'
outputs:
  lastVersion:
    description: 'Project last version'
  deploy:
    description: 'if version is not last takes on the value true'

runs:
  using: 'composite'
  steps:
    - name: Check last version
      run: |
        lastTag=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/OsomePteLtd/${{ inputs.repo }}/tags | jq -r '.[0].name')
        echo "lastVersion=$lastTag" >> $GITHUB_OUTPUT
        echo "last tag ---> $lastTag"
        echo "current tag ---> ${{ inputs.currentTag }}"
        echo "Going to compare the last version in the main branch with deployed version"
        if [ "$lastTag" != "${{ inputs.currentTag }}" ] ; then
          echo "The version in main is fresher than the deployed one"
          echo "deploy=true" >> $GITHUB_OUTPUT
        fi
      shell: bash
