name: CI

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - master

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY_PUBLISHING }}

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest

    outputs:
      node_version: ${{ steps.node.outputs.version }}
      yarn_cache_dir: ${{ steps.yarn.outputs.cache }}

    steps:
      - name: Cancel previous workflow runs
        uses: styfle/cancel-workflow-action@ee9e0f86fb1a4d7029390154477333bf53e41c5e # 0.4.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Export Node.js version
        run: echo ::set-output name=version::$(cat .nvmrc)
        id: node

      - name: Export Yarn cache location
        run: echo ::set-output name=cache::$(yarn cache dir)
        id: yarn

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.node.outputs.version }}'

      - name: Restore caches
        uses: actions/cache@v2
        with:
          path: |
            ${{ needs.setup.outputs.yarn_cache_dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-

      - name: Install dependencies
        run: yarn --frozen-lockfile --no-progress

  static-checks:
    name: Static checks
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '${{ needs.setup.outputs.node_version }}'

      - name: Restore caches
        uses: actions/cache@v2
        with:
          path: |
            ${{ needs.setup.outputs.yarn_cache_dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-

      - name: Install dependencies
        run: yarn --frozen-lockfile --no-progress

      - name: Run lint
        run: yarn lint

      - name: Run Flow
        run: yarn flow

  tests:
    name: Unit tests
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '${{ needs.setup.outputs.node_version }}'

      - name: Restore caches
        uses: actions/cache@v2
        with:
          path: |
            ${{ needs.setup.outputs.yarn_cache_dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-

      - name: Install dependencies
        run: yarn --frozen-lockfile --no-progress

      - name: Run unit tests
        run: yarn test

  publish:
    name: Publish package
    needs:
      - setup
      - static-checks
      - tests
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '${{ needs.setup.outputs.node_version }}'
          registry-url: 'https://registry.npmjs.org'

      - name: Restore caches
        uses: actions/cache@v2
        with:
          path: |
            ${{ needs.setup.outputs.yarn_cache_dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-

      - name: Install dependencies
        run: yarn --frozen-lockfile --no-progress

      - name: Publish package
        run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY_PUBLISHING }}