name: 'Run E2E tests'
description: ''
inputs:
  token:
    description: 'Personal access token'
    required: false
outputs:
  e2e:
    description: 'List of e2e environments'
runs:
  using: 'node12'
  main: './dist/index.js'
