name: 'Bump version'
description: 'Bump application version'
inputs:
  token:
    description: 'Personal access token'
    required: true
  working-directory:
    description: 'Working directory'
    required: false
  newversion:
    description: 'The newversion argument should be a valid semver string'
    default: minor
    required: false
runs:
  using: 'node14'
  main: './dist/index.js'
