name: 'Bump version'
description: 'Bump application version'
inputs:
  token:
    description: 'Personal access token'
    required: true
  working-directory:
    description: 'Working directory'
    required: false
runs:
  using: 'node12'
  main: './dist/index.js'
