name: 'Get E2E stages'
description: ''
inputs:
  environment:
    description: 'Deploy environment'
    required: false
outputs:
  e2e:
    description: 'List of E2E environments'
runs:
  using: 'node18'
  main: './dist/index.js'
