name: 'Lokalise Download'
description: 'Download files from lokalise'
branding:
  icon: 'flag'
  color: 'green'
inputs:
  lokalise-token: # id of input
    description: 'Your CLI/API token for Lokalise'
    required: true
  lokalise-project-id: # id of input
    description: 'Your project ID for Lokalise'
    required: true
  file-path: # id of input
    description: 'The path to the destination folder'
    required: true
    default: 'public/locales'
  format: # id of input
    description: 'The format of the file you want to download'
    required: true
    default: 'json'
  bundle-structure: # id of input
    description: 'The bundle structure'
    required: true
    default: '%LANG_ISO%'
  placeholder-format:
    description: 'Placeholder format of strings'
    required: true
    default: 'i18n'
  trigger:
    description: 'Trigger integration export'
    required: true
    default: 'github'
  add-newline-eof:
    description: 'Enable to add new line at end of file'
    required: true
    default: 'true'
  filter-repositories:
    description: 'Pull requests will be created only for listed repositories'
    required: true
  filter-filenames:
    description: 'Only keys attributed to selected files will be included'
    required: true
  plural-format:
    description: 'Override the default plural format for the file type'
    required: true
    default: 'icu'
  indentation:
    description: 'Provide to override default indentation in supported files'
    required: true
    default: '2sp'
  export-sort:
    description: 'Allowed value are first_added, last_added, last_updated, a_z, z_a'
    required: true
    default: 'a_z'
  original-filename:
    description: 'Use original filenames'
    required: false
    default: true
  directory-prefix:
    description: 'Directory prefix in the bundle'
    required: true
    default: 'public/locales/%LANG_ISO%'

runs:
  using: 'composite'
  steps:
    - name: Install lokalise
      run: |
        curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh
        mv ./bin/lokalise2 /usr/local/bin
        lokalise2 --version
      shell: bash

    - name: Lokalise download
      run: |
        ${{ github.action_path }}/download.sh \
            ${{ inputs.lokalise-token }} \
            ${{ inputs.lokalise-project-id }} \
            ${{ inputs.file-path }} \
            ${{ inputs.format }} \
            ${{ inputs.bundle-structure }} \
            ${{ inputs.placeholder-format }} \
            ${{ inputs.trigger }} \
            ${{ inputs.add-newline-eof }} \
            ${{ inputs.filter-repositories }} \
            ${{ inputs.filter-filenames }} \
            ${{ inputs.plural-format }} \
            ${{ inputs.indentation }} \
            ${{ inputs.export-sort }} \
            ${{ inputs.original-filename }} \
            ${{ inputs.directory-prefix }}
      shell: bash
