name: 'Lokalise Download'
description: 'Download files from lokalise'
branding:
  icon: 'flag'
  color: 'green'
inputs:
  lokalise-token: # id of input
    description: 'Your CLI/API token for Lokalise'
    required: true
  lokalise-project-id: # id of input
    description: 'Your project ID for Lokalise'
    required: true
  file-path: # id of input
    description: 'The path to the destination folder'
    required: true
  format: # id of input
    description: 'The format of the file you want to download'
    required: true
  bundle-structure: # id of input
    description: 'The bundle structure'
    required: true
    default: '/%LANG_ISO%.json'
  original-filename:
    description: 'Use original filenames'
    required: true
    default: false
  placeholder-format:
    description: 'Placeholder format of strings'
    required: true
    default: 'i18n'
  trigger:
    description: 'Trigger integration export'
    required: true
    default: 'github'
runs:
  using: 'composite'
  steps:
    - name: Install lokalise
      run: |
        curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh
        mv ./bin/lokalise2 /usr/local/bin
        lokalise2 --version
      shel: bash

    - name: Lokalise download
      run: ${{ github.action_path }}/download.sh ${{ inputs.lokalise-token }} ${{ inputs.lokalise-project-id }} ${{ inputs.file-path }} ${{ inputs.format }} ${{ inputs.bundle-structure }} ${{ inputs.original-filename }} ${{ inputs.placeholder-format }} ${{ inputs.trigger }}
      shell: bash
