name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        shell: bash -l {0}
        run: nvm install

      - name: Restore cache
        uses: c-hive/gha-npm-cache@v1

      - name: Install dependencies
        run: npx lerna bootstrap

      - name: Run unit tests
        run: npx lerna run test