name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-20.04

    steps:
      - name: Load current commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      
      - name: Check index.js rebuild
        run: |
          diff=$(git diff --name-only)
          if [[ "${diff[*]}" =~ ^(packages\/.*\/.*\/.*.ts) ]] && [[ ! "${diff[*]}" =~ ^(packages\/.*\/.*\/.*.js) ]]; then
            echo "index.ts has been changed but index.js didn't rebuild.\nPlease run:\nnpm i && npm run precommit in the root dir of action"
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: |
          npm ci

      - name: Install dependencies
        run: ./node_modules/.bin/lerna bootstrap

      - name: Run unit tests
        run: ./node_modules/.bin/lerna run test
